project:
  type: website
  output-dir: docs
execute:
  freeze: auto

format:
  html:
    favicon: images/favicon.ico
    page-layout: full
    date-format: "MM YYYY"
    css: styles.css  # Reference your compiled CSS file
    theme: darkly  # Reference theme directly, without SCSS

website:
  title: "Yannick Vinkesteijn"
  site-url: "https://yannickvinkesteijn.com"

  # Navbar configuration for main page navigation
  navbar:
    title: false
    logo: images/logo_tri.svg
    collapse-below: sm
    search: false
    right:
      - icon: envelope
        href: mailto:yannick@vinkesteijn.io
      - icon: linkedin
        href: https://www.linkedin.com/in/yvinkesteijn
      - icon: github
        href: https://github.com/yannick-vinkesteijn

  page-footer:
    center: |
      <br>
      Copyright &copy; 2024 Yannick Vinkesteijn<br>
      This website was created with 
      [![](/images/quarto.png){fig-alt="Quarto" width=65px}](https://quarto.org)
